export type AppPreset = {
  id: string
  name: string
  image: string
  defaultPort: number
  description: string
  longDescription?: string
  category: AppCategory
}

export type AppCategory = 'database' | 'monitoring' | 'proxy' | 'storage' | 'media' | 'home' | 'cms' | 'security' | 'devops' | 'communication' | 'games' | 'other'

export type AppCategoryInfo = {
  id: AppCategory
  label: string
  color: string
}

export const APP_CATEGORIES: AppCategoryInfo[] = [
  { id: 'database', label: 'Databases', color: '#4479A1' },
  { id: 'monitoring', label: 'Monitoring', color: '#F46800' },
  { id: 'proxy', label: 'Proxy & Web', color: '#009639' },
  { id: 'storage', label: 'Storage & Sync', color: '#C72E49' },
  { id: 'media', label: 'Media', color: '#EB564B' },
  { id: 'home', label: 'Home Automation', color: '#41BDF5' },
  { id: 'security', label: 'Security', color: '#175DDC' },
  { id: 'cms', label: 'CMS & Blog', color: '#21759B' },
  { id: 'devops', label: 'DevOps', color: '#FC6D26' },
  { id: 'communication', label: 'Communication', color: '#6C5CE7' },
  { id: 'games', label: 'Game Servers', color: '#9B59B6' },
  { id: 'other', label: 'Other', color: '#6366F1' },
]

export const APP_PRESETS: AppPreset[] = [
  // Databases
  { id: 'redis', name: 'Redis', image: 'redis:alpine', defaultPort: 6379, description: 'In-memory data store', category: 'database' },
  { id: 'postgres', name: 'PostgreSQL', image: 'postgres:16-alpine', defaultPort: 5432, description: 'Relational database', category: 'database' },
  { id: 'mysql', name: 'MySQL', image: 'mysql:8', defaultPort: 3306, description: 'MySQL database', category: 'database' },
  { id: 'mongodb', name: 'MongoDB', image: 'mongo:7', defaultPort: 27017, description: 'NoSQL database', category: 'database' },
  { id: 'mariadb', name: 'MariaDB', image: 'mariadb:11', defaultPort: 3306, description: 'MySQL fork database', category: 'database' },
  { id: 'sqlite', name: 'SQLite', image: 'nouchka/sqlite3:latest', defaultPort: 0, description: 'Lightweight SQL database', category: 'database' },
  { id: 'cockroachdb', name: 'CockroachDB', image: 'cockroachdb/cockroach:v23.1', defaultPort: 8080, description: 'Distributed SQL database', category: 'database' },
  { id: 'influxdb', name: 'InfluxDB', image: 'influxdb:2', defaultPort: 8086, description: 'Time-series database', category: 'database' },
  { id: 'timescaledb', name: 'TimescaleDB', image: 'timescale/timescaledb:latest-pg16', defaultPort: 5432, description: 'Time-series for PostgreSQL', category: 'database' },
  { id: 'clickhouse', name: 'ClickHouse', image: 'clickhouse/clickhouse-server:23', defaultPort: 8123, description: 'Columnar database', category: 'database' },
  { id: 'couchdb', name: 'CouchDB', image: 'couchdb:3', defaultPort: 5984, description: 'NoSQL database', category: 'database' },
  { id: 'couchbase', name: 'Couchbase', image: 'couchbase/server:latest', defaultPort: 8091, description: 'NoSQL database', category: 'database' },
  { id: 'cassandra', name: 'Cassandra', image: 'cassandra:4', defaultPort: 9042, description: 'NoSQL database', category: 'database' },
  { id: 'scylladb', name: 'ScyllaDB', image: 'scylladb/scylla:latest', defaultPort: 9042, description: 'NoSQL database', category: 'database' },
  { id: 'arangodb', name: 'ArangoDB', image: 'arangodb:latest', defaultPort: 8529, description: 'Multi-model DB', category: 'database' },
  { id: 'neo4j', name: 'Neo4j', image: 'neo4j:5', defaultPort: 7474, description: 'Graph database', category: 'database' },
  { id: 'orientdb', name: 'OrientDB', image: 'orientdb:latest', defaultPort: 2480, description: 'NoSQL database', category: 'database' },
  { id: 'rethinkdb', name: 'RethinkDB', image: 'rethinkdb:2.4', defaultPort: 8080, description: 'NoSQL database', category: 'database' },
  { id: 'etcd', name: 'etcd', image: 'bitnami/etcd:latest', defaultPort: 2379, description: 'Key-value store', category: 'database' },
  { id: 'memcached', name: 'Memcached', image: 'memcached:latest', defaultPort: 11211, description: 'Cache server', category: 'database' },
  { id: 'yugabyte', name: 'YugabyteDB', image: 'yugabytedb/yugabyte:latest', defaultPort: 7000, description: 'Distributed SQL', category: 'database' },
  { id: 'presto', name: 'Presto', image: 'trinodb/trino:latest', defaultPort: 8080, description: 'Query engine', category: 'database' },
  { id: 'pgadmin', name: 'pgAdmin', image: 'dpage/pgadmin4:latest', defaultPort: 80, description: 'PostgreSQL admin', category: 'database' },
  { id: 'phpmyadmin', name: 'phpMyAdmin', image: 'phpmyadmin/phpmyadmin:latest', defaultPort: 80, description: 'MySQL admin', category: 'database' },
  { id: 'adminer', name: 'Adminer', image: 'adminer/adminer:latest', defaultPort: 8080, description: 'Database admin', category: 'database' },
  { id: 'dbeaver', name: 'DBeaver', image: 'dbeaver/cloudbeaver:latest', defaultPort: 8978, description: 'SQL client', category: 'database' },
  { id: 'redisinsight', name: 'RedisInsight', image: 'redislabs/redisinsight:latest', defaultPort: 8001, description: 'Redis admin', category: 'database' },

  // Monitoring
  { id: 'grafana', name: 'Grafana', image: 'grafana/grafana:latest', defaultPort: 3000, description: 'Metrics dashboard', category: 'monitoring' },
  { id: 'prometheus', name: 'Prometheus', image: 'prom/prometheus:latest', defaultPort: 9090, description: 'Metrics collection', category: 'monitoring' },
  { id: 'portainer', name: 'Portainer', image: 'portainer/portainer-ce:latest', defaultPort: 9443, description: 'Container management', category: 'monitoring' },
  { id: 'uptimkuma', name: 'Uptime Kuma', image: 'louislam/uptime-kuma:latest', defaultPort: 3001, description: 'Self-hosted monitoring', category: 'monitoring' },
  { id: 'glances', name: 'Glances', image: 'nicolargo/glances:latest', defaultPort: 61208, description: 'System monitoring', category: 'monitoring' },
  { id: 'netdata', name: 'Netdata', image: 'netdata/netdata:latest', defaultPort: 19999, description: 'Real-time monitoring', category: 'monitoring' },
  { id: 'loki', name: 'Grafana Loki', image: 'grafana/loki:latest', defaultPort: 3100, description: 'Log aggregation', category: 'monitoring' },
  { id: 'alertmanager', name: 'Alertmanager', image: 'prom/alertmanager:latest', defaultPort: 9093, description: 'Alert handling', category: 'monitoring' },
  { id: 'thanos', name: 'Thanos', image: 'thanosio/thanos:latest', defaultPort: 10902, description: 'Long-term Prometheus storage', category: 'monitoring' },
  { id: 'cadvisor', name: 'cAdvisor', image: 'gcr.io/cadvisor/cadvisor:latest', defaultPort: 8080, description: 'Container metrics', category: 'monitoring' },
  { id: 'unifi', name: 'UniFi Controller', image: 'linuxserver/unifi-controller:latest', defaultPort: 8080, description: 'Network management', category: 'monitoring' },
  { id: 'speedtest', name: 'Speedtest Tracker', image: 'henrywhitaker3/speedtest-tracker:latest', defaultPort: 80, description: 'Speed monitoring', category: 'monitoring' },
  { id: 'watchtower', name: 'Watchtower', image: 'containrrr/watchtower:latest', defaultPort: 8080, description: 'Container updater', category: 'monitoring' },
  { id: 'cockpit', name: 'Cockpit', image: 'cockpit/ws:latest', defaultPort: 9090, description: 'System admin', category: 'monitoring' },
  { id: 'webmin', name: 'Webmin', image: 'linuxserver/webmin:latest', defaultPort: 10000, description: 'System admin', category: 'monitoring' },

  // Proxy & Web
  { id: 'nginx', name: 'Nginx', image: 'nginx:latest', defaultPort: 80, description: 'Web server', category: 'proxy' },
  { id: 'traefik', name: 'Traefik', image: 'traefik:v3.0', defaultPort: 80, description: 'Reverse proxy', category: 'proxy' },
  { id: 'caddy', name: 'Caddy', image: 'caddy:2', defaultPort: 2015, description: 'Web server with HTTPS', category: 'proxy' },
  { id: 'apache', name: 'Apache', image: 'httpd:2.4', defaultPort: 80, description: 'Web server', category: 'proxy' },
  { id: 'haproxy', name: 'HAProxy', image: 'haproxy:2.8', defaultPort: 80, description: 'Load balancer', category: 'proxy' },
  { id: 'varnish', name: 'Varnish', image: 'varnish:latest', defaultPort: 6081, description: 'HTTP cache', category: 'proxy' },
  { id: 'squid', name: 'Squid', image: 'sameersbn/squid:latest', defaultPort: 3128, description: 'Proxy server', category: 'proxy' },
  { id: 'envoy', name: 'Envoy', image: 'envoyproxy/envoy:latest', defaultPort: 9901, description: 'Service proxy', category: 'proxy' },
  { id: 'nginx-proxy', name: 'Nginx Proxy Manager', image: 'jc21/nginx-proxy-manager:latest', defaultPort: 81, description: 'Reverse proxy manager', category: 'proxy' },

  // Storage
  { id: 'minio', name: 'MinIO', image: 'minio/minio:latest', defaultPort: 9000, description: 'S3-compatible storage', category: 'storage' },
  { id: 'registry', name: 'Docker Registry', image: 'registry:2', defaultPort: 5000, description: 'Private container registry', category: 'storage' },
  { id: 'nextcloud', name: 'Nextcloud', image: 'nextcloud:latest', defaultPort: 80, description: 'File sync & share', category: 'storage' },
  { id: 'syncthing', name: 'Syncthing', image: 'syncthing/syncthing:latest', defaultPort: 8384, description: 'File synchronization', category: 'storage' },
  { id: 'filebrowser', name: 'File Browser', image: 'filebrowser/filebrowser:latest', defaultPort: 80, description: 'Web file manager', category: 'storage' },
  { id: 'owncloud', name: 'Owncloud', image: 'owncloud/server:latest', defaultPort: 8080, description: 'File sync & share', category: 'storage' },
  { id: 'seafile', name: 'Seafile', image: 'seafileltd/seafile-mc:latest', defaultPort: 8080, description: 'File sync & share', category: 'storage' },
  { id: 'pydio', name: 'Pydio', image: 'pydio/pydio-core:latest', defaultPort: 8080, description: 'File sync & share', category: 'storage' },
  { id: 'duplicati', name: 'Duplicati', image: 'linuxserver/duplicati:latest', defaultPort: 8200, description: 'Backup software', category: 'storage' },
  { id: 'restic', name: 'Restic', image: 'restic/rest-server:latest', defaultPort: 8000, description: 'Backup repository', category: 'storage' },
  { id: 'borg', name: 'Borg Backup', image: 'linuxserver/borgmatic:latest', defaultPort: 8080, description: 'Backup software', category: 'storage' },
  { id: 'veejay', name: 'VeeJay', image: 'linuxserver/veejay:latest', defaultPort: 8084, description: 'Video sampler', category: 'storage' },

  // Media
  { id: 'plex', name: 'Plex', image: 'plexinc/pms-docker:latest', defaultPort: 32400, description: 'Media server', category: 'media' },
  { id: 'jellyfin', name: 'Jellyfin', image: 'jellyfin/jellyfin:latest', defaultPort: 8096, description: 'Media server', category: 'media' },
  { id: 'emby', name: 'Emby', image: 'emby/embyserver:latest', defaultPort: 8096, description: 'Media server', category: 'media' },
  { id: 'radarr', name: 'Radarr', image: 'linuxserver/radarr:latest', defaultPort: 7878, description: 'Movie downloader', category: 'media' },
  { id: 'sonarr', name: 'Sonarr', image: 'linuxserver/sonarr:latest', defaultPort: 8989, description: 'TV show downloader', category: 'media' },
  { id: 'lidarr', name: 'Lidarr', image: 'linuxserver/lidarr:latest', defaultPort: 8686, description: 'Music downloader', category: 'media' },
  { id: 'readarr', name: 'Readarr', image: 'linuxserver/readarr:latest', defaultPort: 8787, description: 'Ebook downloader', category: 'media' },
  { id: 'qbittorrent', name: 'qBittorrent', image: 'linuxserver/qbittorrent:latest', defaultPort: 8080, description: 'Torrent client', category: 'media' },
  { id: 'transmission', name: 'Transmission', image: 'linuxserver/transmission:latest', defaultPort: 9091, description: 'Torrent client', category: 'media' },
  { id: 'deluge', name: 'Deluge', image: 'linuxserver/deluge:latest', defaultPort: 8112, description: 'Torrent client', category: 'media' },
  { id: 'tautulli', name: 'Tautulli', image: 'tautulli/tautulli:latest', defaultPort: 8181, description: 'Plex statistics', category: 'media' },
  { id: 'jackett', name: 'Jackett', image: 'linuxserver/jackett:latest', defaultPort: 9117, description: 'Torrent indexer', category: 'media' },
  { id: 'bazarr', name: 'Bazarr', image: 'linuxserver/bazarr:latest', defaultPort: 6767, description: 'Subtitle downloader', category: 'media' },
  { id: 'overseerr', name: 'Overseerr', image: 'linuxserver/overseerr:latest', defaultPort: 5055, description: 'Request management', category: 'media' },
  { id: 'metube', name: 'MeTube', image: 'axcore/metube:latest', defaultPort: 8081, description: 'YouTube downloader', category: 'media' },
  { id: 'sabnzbd', name: 'SABnzbd', image: 'linuxserver/sabnzbd:latest', defaultPort: 8080, description: 'Usenet downloader', category: 'media' },
  { id: 'nzbget', name: 'NZBGet', image: 'linuxserver/nzbget:latest', defaultPort: 6789, description: 'Usenet downloader', category: 'media' },
  { id: 'ombi', name: 'Ombi', image: 'linuxserver/ombi:latest', defaultPort: 3579, description: 'Media requests', category: 'media' },
  { id: 'photoprism', name: 'PhotoPrism', image: 'photoprism/photoprism:latest', defaultPort: 2342, description: 'Photo gallery', category: 'media' },
  { id: 'immich', name: 'Immich', image: 'ghcr.io/immich-app/immich-server:latest', defaultPort: 2283, description: 'Photo backup', category: 'media' },
  { id: 'librephotos', name: 'LibrePhotos', image: 'librephotos/librephotos:latest', defaultPort: 3000, description: 'Photo gallery', category: 'media' },
  { id: 'piwigo', name: 'Piwigo', image: 'piwigo/piwigo:latest', defaultPort: 80, description: 'Photo gallery', category: 'media' },
  { id: 'snapdrop', name: 'Snapdrop', image: 'linuxserver/snapdrop:latest', defaultPort: 80, description: 'File sharing', category: 'media' },

  // Home Automation
  { id: 'homeassistant', name: 'Home Assistant', image: 'homeassistant/home-assistant:stable', defaultPort: 8123, description: 'Home automation', category: 'home' },
  { id: 'iobroker', name: 'ioBroker', image: 'iobroker/iobroker:latest', defaultPort: 8081, description: 'Home automation', category: 'home' },
  { id: 'openhab', name: 'openHAB', image: 'openhab/openhab:4', defaultPort: 8080, description: 'Home automation', category: 'home' },
  { id: 'node-red', name: 'Node-RED', image: 'nodered/node-red:latest', defaultPort: 1880, description: 'Flow-based programming', category: 'home' },
  { id: 'mosquitto', name: 'Mosquitto', image: 'eclipse-mosquitto:2', defaultPort: 1883, description: 'MQTT broker', category: 'home' },
  { id: 'zigbee2mqtt', name: 'Zigbee2MQTT', image: 'koenkk/zigbee2mqtt:latest', defaultPort: 8080, description: 'Zigbee bridge', category: 'home' },
  { id: 'frigate', name: 'Frigate', image: 'ghcr.io/blakeblackscreen/frigate:latest', defaultPort: 5000, description: 'NVR with AI', category: 'home' },
  { id: 'scrypted', name: 'Scrypted', image: 'koush/scrypted:latest', defaultPort: 10443, description: 'Video analytics', category: 'home' },
  { id: 'homebridge', name: 'HomeBridge', image: 'homebridge/homebridge:latest', defaultPort: 8581, description: 'HomeKit bridge', category: 'home' },
  { id: 'homeassistant-core', name: 'Home Assistant Core', image: 'homeassistant/amd64-homeassistant:stable', defaultPort: 8123, description: 'Home automation', category: 'home' },

  // Security
  { id: 'adguard', name: 'AdGuard Home', image: 'adguard/adguardhome:latest', defaultPort: 3000, description: 'DNS ad blocker', category: 'security' },
  { id: 'vaultwarden', name: 'Vaultwarden', image: 'vaultwarden/server:latest', defaultPort: 80, description: 'Password manager', category: 'security' },
  { id: 'authentik', name: 'Authentik', image: 'ghcr.io/goauthentik/server:latest', defaultPort: 9000, description: 'Identity provider', category: 'security' },
  { id: 'authelia', name: 'Authelia', image: 'authelia/authelia:latest', defaultPort: 9091, description: 'Authentication proxy', category: 'security' },
  { id: 'traefik-forward-auth', name: 'Traefik Forward Auth', image: 'thomseddon/traefik-forward-auth:latest', defaultPort: 4181, description: 'OAuth proxy', category: 'security' },
  { id: 'wireguard', name: 'WireGuard', image: 'linuxserver/wireguard:latest', defaultPort: 51820, description: 'VPN', category: 'security' },
  { id: 'openvpn', name: 'OpenVPN', image: 'linuxserver/openvpn-as:latest', defaultPort: 943, description: 'VPN', category: 'security' },
  { id: 'tailscale', name: 'Tailscale', image: 'tailscale/tailscale:latest', defaultPort: 41641, description: 'VPN', category: 'security' },
  { id: 'crowdsec', name: 'CrowdSec', image: 'crowdsecurity/crowdsec:latest', defaultPort: 8080, description: 'Security engine', category: 'security' },
  { id: 'fail2ban', name: 'Fail2Ban', image: 'linuxserver/fail2ban:latest', defaultPort: 0, description: 'Intrusion prevention', category: 'security' },
  { id: 'clamav', name: 'ClamAV', image: 'linuxserver/clamav:latest', defaultPort: 3310, description: 'Antivirus', category: 'security' },
  { id: 'keycloak', name: 'Keycloak', image: 'quay.io/keycloak/keycloak:latest', defaultPort: 8080, description: 'Identity management', category: 'security' },
  { id: 'dex', name: 'Dex', image: 'ghcr.io/dexidp/dex:latest', defaultPort: 5556, description: 'Identity provider', category: 'security' },
  { id: 'oauth2-proxy', name: 'OAuth2 Proxy', image: 'oauth2-proxy/oauth2-proxy:latest', defaultPort: 4180, description: 'Auth proxy', category: 'security' },
  { id: 'casdoor', name: 'Casdoor', image: 'casdoor/casdoor:latest', defaultPort: 8000, description: 'Auth platform', category: 'security' },
  { id: 'logto', name: 'Logto', image: 'logto/io.logto.sdk.local:latest', defaultPort: 3001, description: 'Auth platform', category: 'security' },

  // CMS
  { id: 'wordpress', name: 'WordPress', image: 'wordpress:latest', defaultPort: 80, description: 'CMS platform', category: 'cms' },
  { id: 'ghost', name: 'Ghost', image: 'ghost:5-alpine', defaultPort: 2368, description: 'Publishing platform', category: 'cms' },
  { id: 'strapi', name: 'Strapi', image: 'strapi/strapi:latest', defaultPort: 1337, description: 'Headless CMS', category: 'cms' },
  { id: 'directus', name: 'Directus', image: 'directus/directus:latest', defaultPort: 8055, description: 'Headless CMS', category: 'cms' },
  { id: 'joomla', name: 'Joomla', image: 'joomla:3-apache', defaultPort: 80, description: 'CMS platform', category: 'cms' },
  { id: 'drupal', name: 'Drupal', image: 'drupal:latest', defaultPort: 80, description: 'CMS platform', category: 'cms' },
  { id: 'grav', name: 'Grav', image: 'getgrav/grav:latest', defaultPort: 80, description: 'Flat-file CMS', category: 'cms' },
  { id: 'hugo', name: 'Hugo', image: 'klakegg/hugo:latest', defaultPort: 1313, description: 'Static site generator', category: 'cms' },
  { id: 'keystone', name: 'Keystone', image: 'keystonejs/keystone:latest', defaultPort: 3000, description: 'Headless CMS', category: 'cms' },
  { id: 'sanity', name: 'Sanity', image: 'sanity:latest', defaultPort: 3333, description: 'Headless CMS', category: 'cms' },
  { id: 'prismic', name: 'Prismic', image: 'prismicio/hub:latest', defaultPort: 1313, description: 'Headless CMS', category: 'cms' },
  { id: 'storyblok', name: 'Storyblok', image: 'storyblok/storyblok:latest', defaultPort: 3000, description: 'Headless CMS', category: 'cms' },
  { id: 'squidex', name: 'Squidex', image: 'squidex/squidex:latest', defaultPort: 80, description: 'Headless CMS', category: 'cms' },
  { id: 'apostrophe', name: 'Apostrophe', image: 'apostrophecms/apostrophe:latest', defaultPort: 3000, description: 'CMS platform', category: 'cms' },
  { id: 'payload', name: 'Payload', image: 'payloadcms/payload:latest', defaultPort: 3000, description: 'Headless CMS', category: 'cms' },
  { id: 'wikijs', name: 'Wiki.js', image: 'requarks/wiki:latest', defaultPort: 3000, description: 'Wiki', category: 'cms' },
  { id: 'bookstack', name: 'BookStack', image: 'linuxserver/bookstack:latest', defaultPort: 80, description: 'Wiki', category: 'cms' },
  { id: 'xwiki', name: 'XWiki', image: 'xwiki:latest', defaultPort: 8080, description: 'Wiki', category: 'cms' },
  { id: 'dokuwiki', name: 'DokuWiki', image: 'linuxserver/dokuwiki:latest', defaultPort: 80, description: 'Wiki', category: 'cms' },
  { id: 'mediawiki', name: 'MediaWiki', image: 'mediawiki:latest', defaultPort: 80, description: 'Wiki', category: 'cms' },

  // DevOps
  { id: 'gitlab', name: 'GitLab', image: 'gitlab/gitlab-ce:latest', defaultPort: 80, description: 'DevOps platform', category: 'devops' },
  { id: 'gitea', name: 'Gitea', image: 'gitea/gitea:latest', defaultPort: 3000, description: 'Self-hosted Git', category: 'devops' },
  { id: 'forgejo', name: 'Forgejo', image: 'codeberg.org/forgejo/forgejo:latest', defaultPort: 3000, description: 'Self-hosted Git', category: 'devops' },
  { id: 'jenkins', name: 'Jenkins', image: 'jenkins/jenkins:lts', defaultPort: 8080, description: 'CI/CD', category: 'devops' },
  { id: 'drone', name: 'Drone', image: 'drone/drone:2', defaultPort: 80, description: 'CI/CD', category: 'devops' },
  { id: 'woodpecker', name: 'Woodpecker', image: 'woodpeckerci/woodpecker-server:latest', defaultPort: 8000, description: 'CI/CD', category: 'devops' },
  { id: 'argocd', name: 'Argo CD', image: 'argoproj/argo-cd:latest', defaultPort: 8080, description: 'GitOps', category: 'devops' },
  { id: 'gitlab-runner', name: 'GitLab Runner', image: 'gitlab/gitlab-runner:latest', defaultPort: 0, description: 'CI/CD runner', category: 'devops' },
  { id: 'harbor', name: 'Harbor', image: 'goharbor/harbor-core:v2.9', defaultPort: 80, description: 'Container registry', category: 'devops' },
  { id: 'sonarqube', name: 'SonarQube', image: 'sonarqube:latest', defaultPort: 9000, description: 'Code quality', category: 'devops' },
  { id: 'nexus', name: 'Nexus Repository', image: 'sonatype/nexus3:latest', defaultPort: 8081, description: 'Artifact repository', category: 'devops' },
  { id: 'tekton', name: 'Tekton', image: 'gcr.io/tekton-releases/dashboard:latest', defaultPort: 9097, description: 'CI/CD', category: 'devops' },
  { id: 'bitwarden', name: 'Bitwarden', image: 'bitwardenrs/server:latest', defaultPort: 80, description: 'Password manager', category: 'devops' },
  { id: 'rancher', name: 'Rancher', image: 'rancher/rancher:latest', defaultPort: 80, description: 'Kubernetes manager', category: 'devops' },
  { id: 'k3s', name: 'K3s', image: 'rancher/k3s:latest', defaultPort: 6443, description: 'Lightweight K8s', category: 'devops' },
  { id: 'vault', name: 'Vault', image: 'hashicorp/vault:latest', defaultPort: 8200, description: 'Secrets management', category: 'devops' },
  { id: 'consul', name: 'Consul', image: 'hashicorp/consul:latest', defaultPort: 8500, description: 'Service discovery', category: 'devops' },
  { id: 'nomad', name: 'Nomad', image: 'hashicorp/nomad:latest', defaultPort: 4646, description: 'Workload orchestrator', category: 'devops' },
  { id: 'localstack', name: 'LocalStack', image: 'localstack/localstack:latest', defaultPort: 4566, description: 'Fully local AWS cloud stack', category: 'devops' },
  { id: 'terraform', name: 'Terraform', image: 'hashicorp/terraform:latest', defaultPort: 0, description: 'Infrastructure-as-code automation', category: 'devops' },
  { id: 'ansible', name: 'Ansible', image: 'ansible/ansible:latest', defaultPort: 0, description: 'Agentless configuration management', category: 'devops' },
  { id: 'packer', name: 'Packer', image: 'hashicorp/packer:latest', defaultPort: 0, description: 'Golden image builder', category: 'devops' },
  { id: 'waypoint', name: 'Waypoint', image: 'hashicorp/waypoint:latest', defaultPort: 9702, description: 'App deployment workflows', category: 'devops' },
  { id: 'boundary', name: 'Boundary', image: 'hashicorp/boundary:latest', defaultPort: 9200, description: 'Zero-trust access proxy', category: 'devops' },
  { id: 'gocd', name: 'GoCD', image: 'gocd/gocd-server:latest', defaultPort: 8153, description: 'Opinionated CI/CD server', category: 'devops' },
  { id: 'spinnaker', name: 'Spinnaker', image: 'armory/spinnaker:latest', defaultPort: 8084, description: 'Multi-cloud CD platform', category: 'devops' },
  { id: 'flux', name: 'Flux', image: 'fluxcd/flux:latest', defaultPort: 3030, description: 'GitOps CD for Kubernetes', category: 'devops' },
  { id: 'dagger', name: 'Dagger', image: 'dagger/dagger:latest', defaultPort: 0, description: 'Portable CI/CD pipelines', category: 'devops' },

  // Communication
  { id: 'mattermost', name: 'Mattermost', image: 'mattermost/mattermost-team-edition:latest', defaultPort: 8065, description: 'Team chat', category: 'communication' },
  { id: 'rocketchat', name: 'Rocket.Chat', image: 'rocket.chat:latest', defaultPort: 3000, description: 'Team chat', category: 'communication' },
  { id: 'element', name: 'Element', image: 'vectorim/element-web:latest', defaultPort: 80, description: 'Matrix client', category: 'communication' },
  { id: 'synapse', name: 'Synapse', image: 'matrixdotorg/synapse:latest', defaultPort: 8008, description: 'Matrix server', category: 'communication' },
  { id: 'zulip', name: 'Zulip', image: 'zulip/zulip:latest', defaultPort: 80, description: 'Team chat', category: 'communication' },
  { id: 'jitsi', name: 'Jitsi', image: 'jitsi/web:latest', defaultPort: 80, description: 'Video conferencing', category: 'communication' },
  { id: 'bigbluebutton', name: 'BigBlueButton', image: 'bigbluebutton/bbb-web:latest', defaultPort: 80, description: 'Video conferencing', category: 'communication' },
  { id: 'mumble', name: 'Mumble', image: 'linuxserver/mumble:latest', defaultPort: 64738, description: 'Voice chat', category: 'communication' },
  { id: 'teamspeak', name: 'TeamSpeak', image: 'linuxserver/teamspeak:latest', defaultPort: 9987, description: 'Voice chat', category: 'communication' },
  { id: 'signal', name: 'Signal', image: 'signalapp/Signal-Server:latest', defaultPort: 8080, description: 'Signal server', category: 'communication' },
  { id: 'matrix', name: 'Conduit', image: 'matrixconduit/conduit:latest', defaultPort: 6167, description: 'Matrix server', category: 'communication' },
  { id: 'hydrogen', name: 'Hydrogen', image: 'vector-im/hydrogen-web:latest', defaultPort: 8080, description: 'Matrix client', category: 'communication' },
  { id: 'nheko', name: 'Nheko', image: 'nheko/nheko-reborn:latest', defaultPort: 8080, description: 'Matrix client', category: 'communication' },
  { id: 'weechat', name: 'WeeChat', image: 'linuxserver/weechat:latest', defaultPort: 8080, description: 'IRC client', category: 'communication' },
  { id: 'znc', name: 'ZNC', image: 'linuxserver/znc:latest', defaultPort: 6667, description: 'IRC bouncer', category: 'communication' },
  { id: 'inspircd', name: 'InspIRCd', image: 'linuxserver/inspircd:latest', defaultPort: 6667, description: 'IRC server', category: 'communication' },
  { id: 'unrealircd', name: 'UnrealIRCd', image: 'linuxserver/unrealircd:latest', defaultPort: 6667, description: 'IRC server', category: 'communication' },
  { id: 'prosody', name: 'Prosody', image: 'linuxserver/prosody:latest', defaultPort: 5222, description: 'XMPP server', category: 'communication' },
  { id: 'ejabberd', name: 'Ejabberd', image: 'ejabberd/ecs:latest', defaultPort: 5222, description: 'XMPP server', category: 'communication' },
  { id: 'matterbridge', name: 'Matterbridge', image: '42wim/matterbridge:latest', defaultPort: 8080, description: 'Bridge chat platforms', category: 'communication' },
  { id: 'chatwork', name: 'ChatWork', image: 'chatwork/chatwork:latest', defaultPort: 80, description: 'Team chat', category: 'communication' },
  { id: 'typetalk', name: 'Typetalk', image: 'nulab/typetalk:latest', defaultPort: 80, description: 'Team chat', category: 'communication' },
  { id: 'gitter', name: 'Gitter', image: 'gitterHQ/gitter:latest', defaultPort: 80, description: 'Team chat', category: 'communication' },
  { id: 'flock', name: 'Flock', image: 'flock/flock:latest', defaultPort: 80, description: 'Team chat', category: 'communication' },
  { id: 'twist', name: 'Twist', image: 'doist/twist:latest', defaultPort: 80, description: 'Team chat', category: 'communication' },

  // Other
  { id: 'rabbitmq', name: 'RabbitMQ', image: 'rabbitmq:3-management', defaultPort: 5672, description: 'Message broker', category: 'other' },
  { id: 'n8n', name: 'n8n', image: 'n8nio/n8n:latest', defaultPort: 5678, description: 'Workflow automation', category: 'other' },
  { id: 'gotify', name: 'Gotify', image: 'gotify/server:latest', defaultPort: 80, description: 'Notification server', category: 'other' },
  { id: 'ntfy', name: 'Ntfy', image: 'binwiederhier/ntfy:latest', defaultPort: 80, description: 'Notification server', category: 'other' },
  { id: 'calcom', name: 'Cal.com', image: 'calcom/calcom:latest', defaultPort: 3000, description: 'Scheduling', category: 'other' },
  { id: 'linkding', name: 'linkding', image: 'sissbruecker/linkding:latest', defaultPort: 8080, description: 'Bookmark manager', category: 'other' },
  { id: 'shlink', name: 'Shlink', image: 'shlinkio/shlink:latest', defaultPort: 8080, description: 'URL shortener', category: 'other' },
  { id: 'wallabag', name: 'Wallabag', image: 'wallabag/wallabag:latest', defaultPort: 80, description: 'Read later', category: 'other' },
  { id: 'freshrss', name: 'FreshRSS', image: 'linuxserver/freshrss:latest', defaultPort: 80, description: 'RSS reader', category: 'other' },
  { id: 'miniflux', name: 'Miniflux', image: 'miniflux/miniflux:latest', defaultPort: 8080, description: 'RSS reader', category: 'other' },
  { id: 'vikunja', name: 'Vikunja', image: 'vikunja/vikunja:latest', defaultPort: 3456, description: 'Task manager', category: 'other' },
  { id: 'wekan', name: 'Wekan', image: 'wekan/wekan:latest', defaultPort: 8080, description: 'Kanban board', category: 'other' },
  { id: 'plane', name: 'Plane', image: 'plane/app:latest', defaultPort: 3000, description: 'Project management', category: 'other' },
  { id: 'kanboard', name: 'Kanboard', image: 'kanboard/kanboard:latest', defaultPort: 80, description: 'Kanban board', category: 'other' },
  { id: 'trilium', name: 'Trilium', image: 'zadam/trilium:latest', defaultPort: 8080, description: 'Notes', category: 'other' },
  { id: 'appwrite', name: 'Appwrite', image: 'appwrite/appwrite:latest', defaultPort: 80, description: 'Backend platform', category: 'other' },
  { id: 'budibase', name: 'Budibase', image: 'budibase/budibase:latest', defaultPort: 10000, description: 'Low-code platform', category: 'other' },
  { id: 'tooljet', name: 'ToolJet', image: 'tooljet/tooljet:latest', defaultPort: 3000, description: 'Low-code platform', category: 'other' },
  { id: 'appsmith', name: 'Appsmith', image: 'appsmith/appsmith-ce:latest', defaultPort: 80, description: 'Low-code platform', category: 'other' },
  { id: 'umami', name: 'Umami', image: 'umamisoftware/umami:postgresql-latest', defaultPort: 3000, description: 'Analytics', category: 'other' },
  { id: 'plausible', name: 'Plausible', image: 'plausible/analytics:latest', defaultPort: 8000, description: 'Analytics', category: 'other' },
  { id: 'matomo', name: 'Matomo', image: 'matomo:latest', defaultPort: 80, description: 'Analytics', category: 'other' },
  { id: 'countly', name: 'Countly', image: 'countly/countly-server:latest', defaultPort: 6001, description: 'Analytics', category: 'other' },
  { id: 'posthog', name: 'PostHog', image: 'posthog/posthog:latest', defaultPort: 8000, description: 'Product analytics', category: 'other' },
  { id: 'ackee', name: 'Ackee', image: 'electerious/ackee:latest', defaultPort: 3000, description: 'Analytics', category: 'other' },
  { id: 'fathom', name: 'Fathom', image: 'usefathom/fathom:latest', defaultPort: 8080, description: 'Analytics', category: 'other' },
  { id: 'metabase', name: 'Metabase', image: 'metabase/metabase:latest', defaultPort: 3000, description: 'BI tool', category: 'other' },
  { id: 'superset', name: 'Superset', image: 'apache/superset:latest', defaultPort: 8088, description: 'BI tool', category: 'other' },
  { id: 'redash', name: 'Redash', image: 'redash/redash:latest', defaultPort: 5000, description: 'BI tool', category: 'other' },
  { id: 'jupyter', name: 'Jupyter', image: 'jupyter/base-notebook:latest', defaultPort: 8888, description: 'Notebook server', category: 'other' },
  { id: 'rstudio', name: 'RStudio', image: 'rocker/rstudio:latest', defaultPort: 8787, description: 'R IDE', category: 'other' },
  { id: 'code-server', name: 'Code Server', image: 'codercom/code-server:latest', defaultPort: 8443, description: 'VS Code in browser', category: 'other' },
  { id: 'streamlit', name: 'Streamlit', image: 'streamlit/streamlit:latest', defaultPort: 8501, description: 'ML web apps', category: 'other' },
  { id: 'mlflow', name: 'MLflow', image: 'mlflow:latest', defaultPort: 5000, description: 'ML tracking', category: 'other' },
  { id: 'dask', name: 'Dask', image: 'dask/dask:latest', defaultPort: 8787, description: 'Distributed computing', category: 'other' },
  { id: 'kafka', name: 'Kafka', image: 'confluentinc/cp-kafka:latest', defaultPort: 9092, description: 'Message streaming', category: 'other' },
  { id: 'pulsar', name: 'Pulsar', image: 'apachepulsar/pulsar:latest', defaultPort: 6650, description: 'Message streaming', category: 'other' },
  { id: 'nats', name: 'NATS', image: 'nats:latest', defaultPort: 4222, description: 'Message broker', category: 'other' },
  { id: 'emqx', name: 'EMQX', image: 'emqx/emqx:latest', defaultPort: 1883, description: 'MQTT broker', category: 'other' },
  { id: 'vernemq', name: 'VerneMQ', image: 'vernemq/vernemq:latest', defaultPort: 8888, description: 'MQTT broker', category: 'other' },
  { id: 'airflow', name: 'Airflow', image: 'apache/airflow:latest', defaultPort: 8080, description: 'Workflow orchestration', category: 'other' },
  { id: 'prefect', name: 'Prefect', image: 'prefecthq/prefect:latest', defaultPort: 4200, description: 'Workflow orchestration', category: 'other' },
  { id: 'dagster', name: 'Dagster', image: 'dagster/dagster:latest', defaultPort: 3000, description: 'Workflow orchestration', category: 'other' },
  { id: 'temporal', name: 'Temporal', image: 'temporalio/temporal:latest', defaultPort: 7233, description: 'Durable workflow engine', category: 'other' },
  { id: 'pipedream', name: 'PipeDream', image: 'pipedream/pipedream:latest', defaultPort: 3000, description: 'Workflow automation', category: 'other' },
  { id: 'activepieces', name: 'Activepieces', image: 'activepieces/activepieces:latest', defaultPort: 3000, description: 'Workflow automation', category: 'other' },
  { id: 'hub', name: 'Dopr', image: 'dopr/hub:latest', defaultPort: 3000, description: 'Workflow automation', category: 'other' },
  { id: 'webiny', name: 'Webiny', image: 'webiny/webiny-serverless-cms:latest', defaultPort: 9000, description: 'Headless CMS', category: 'other' },
  { id: 'verdaccio', name: 'Verdaccio', image: 'verdaccio/verdaccio:latest', defaultPort: 4873, description: 'Private NPM registry', category: 'other' },
  { id: 'artifactory', name: 'Artifactory', image: 'jfrog/artifactory-oss:latest', defaultPort: 8082, description: 'Artifact repo', category: 'other' },
  { id: 'ghorg', name: 'ghorg', image: 'thegeeklab/ghorg:latest', defaultPort: 80, description: 'GitOps', category: 'other' },

  // Game Servers
  { id: 'minecraft', name: 'Minecraft', image: 'itzg/minecraft-server:latest', defaultPort: 25565, description: 'Minecraft game server', category: 'games', longDescription: 'A popular sandbox game server supporting Java and Bedrock editions with modding capabilities.' },
  { id: 'minecraft-bedrock', name: 'Minecraft Bedrock', image: 'itzg/minecraft-bedrock-server:latest', defaultPort: 19132, description: 'Minecraft Bedrock server', category: 'games', longDescription: 'Official Minecraft Bedrock edition server for Windows 10, mobile, and console players.' },
  { id: 'valheim', name: 'Valheim', image: 'lloesche/valheim-server:latest', defaultPort: 2456, description: 'Valheim game server', category: 'games', longDescription: 'Viking-themed survival game server with world persistence and mods support.' },
  { id: 'terraria', name: 'Terraria', image: 'hexaangel76/terraria:latest', defaultPort: 7777, description: 'Terraria game server', category: 'games', longDescription: '2D sandbox adventure game server with TShock plugin support.' },
  { id: 'rust-game', name: 'Rust', image: 'cm2network/rust:latest', defaultPort: 28015, description: 'Rust game server', category: 'games', longDescription: 'Survival game server with multiplayer support. Requires significant resources.' },
  { id: 'ark', name: 'ARK: Survival Evolved', image: 'arkprotocol/ark-server:latest', defaultPort: 27015, description: 'ARK game server', category: 'games', longDescription: 'Dinosaur survival game server with map and mod support.' },
  { id: 'factorio', name: 'Factorio', image: 'factoriotools/factorio:latest', defaultPort: 34197, description: 'Factorio game server', category: 'games', longDescription: 'Factory automation game server with headless mode and saves.' },
  { id: '7days', name: '7 Days to Die', image: 'ich777/steamcmd:latest', defaultPort: 26900, description: '7 Days to Die server', category: 'games', longDescription: 'Survival horror game server with persistent worlds and mods.' },
  { id: 'palworld', name: 'Palworld', image: 'ich777/steamcmd:latest', defaultPort: 27015, description: 'Palworld game server', category: 'games', longDescription: 'Monster collecting and survival game server with pals.' },
  { id: 'sons-of-the-forest', name: 'Sons of the Forest', image: 'ich777/steamcmd:latest', defaultPort: 27015, description: 'Sons of the Forest server', category: 'games', longDescription: 'Survival horror game server with building mechanics.' },
  { id: 'cs2', name: 'Counter-Strike 2', image: 'cm2network/cs2:latest', defaultPort: 27015, description: 'CS2 game server', category: 'games', longDescription: 'Popular FPS game server with competitive and casual modes.' },
  { id: 'csgo', name: 'CS:GO', image: 'cm2network/csgo:latest', defaultPort: 27015, description: 'CS:GO game server', category: 'games', longDescription: 'Classic counter-strike game server with matchmaking support.' },
  { id: 'gmod', name: 'Garry\'s Mod', image: 'cm2network/gmod:latest', defaultPort: 27015, description: 'GMod game server', category: 'games', longDescription: 'Physics sandbox game server with extensive mod support.' },
  { id: 'l4d2', name: 'Left 4 Dead 2', image: 'cm2network/l4d2:latest', defaultPort: 27015, description: 'L4D2 game server', category: 'games', longDescription: 'Co-op zombie shooter server with campaign and versus modes.' },
  { id: 'tf2', name: 'Team Fortress 2', image: 'cm2network/tf2:latest', defaultPort: 27015, description: 'TF2 game server', category: 'games', longDescription: 'Classic class-based shooter server with custom maps support.' },
  { id: 'fivem', name: 'FiveM', image: 'qchar/fivem:latest', defaultPort: 30110, description: 'FiveM server', category: 'games', longDescription: 'GTA V multiplayer modification server.' },
  { id: 'redm', name: 'RedM', image: 'qchar/redm:latest', defaultPort: 30120, description: 'RedM server', category: 'games', longDescription: 'Red Dead Redemption 2 multiplayer server.' },
  { id: 'minetest', name: 'Minetest', image: 'linuxserver/minetest:latest', defaultPort: 30000, description: 'Minetest server', category: 'games', longDescription: 'Open source Minecraft-like voxel game server.' },
  { id: 'spigot', name: 'Spigot', image: 'itzg/minecraft-server:latest', defaultPort: 25565, description: 'Spigot server', category: 'games', longDescription: 'Popular Minecraft server software with plugin support.' },
  { id: 'paper', name: 'PaperMC', image: 'itzg/minecraft-server:latest', defaultPort: 25565, description: 'PaperMC server', category: 'games', longDescription: 'High-performance Minecraft server fork with plugins.' },
  { id: 'purpur', name: 'Purpur', image: 'purpurmc/purpur:latest', defaultPort: 25565, description: 'Purpur server', category: 'games', longDescription: 'Fork of PaperMC with extensive configuration options.' },
  { id: 'bungeecord', name: 'BungeeCord', image: 'itzg/bungeecord:latest', defaultPort: 25577, description: 'BungeeCord proxy', category: 'games', longDescription: 'Minecraft proxy server for connecting multiple servers.' },
  { id: 'velocity', name: 'Velocity', image: 'velocitymc/velocity:latest', defaultPort: 25577, description: 'Velocity proxy', category: 'games', longDescription: 'Modern Minecraft proxy server with plugin support.' },
  { id: 'pterodactyl', name: 'Pterodactyl', image: 'pterodactyl/panel:latest', defaultPort: 80, description: 'Pterodactyl Panel', category: 'games', longDescription: 'Game server management panel with Docker support.' },
  { id: 'satisfactory', name: 'Satisfactory', image: 'wolveix/satisfactory:latest', defaultPort: 27000, description: 'Satisfactory server', category: 'games', longDescription: 'Factory building game server with automation.' },
  { id: 'raft', name: 'Raft', image: 'danielvanhaven/raft-server:latest', defaultPort: 27015, description: 'Raft server', category: 'games', longDescription: 'Survival game on a raft in the ocean with crafting.' },
  { id: 'eco', name: 'Eco', image: 'StrangeLoopGames/eco-server:latest', defaultPort: 3000, description: 'Eco server', category: 'games', longDescription: 'Medieval simulation game server with economy.' },
  { id: 'starbound', name: 'Starbound', image: 'linuxserver/starbound:latest', defaultPort: 21025, description: 'Starbound server', category: 'games', longDescription: 'Space sandbox game server.' },
  { id: 'pz', name: 'Project Zomboid', image: 'jamesits/projectzomboid:latest', defaultPort: 27015, description: 'Project Zomboid server', category: 'games', longDescription: 'Top-down survival game server with zombies.' },
  { id: 'dontstarve', name: "Don't Starve", image: 'jamesits/dontstarve:latest', defaultPort: 10999, description: "Don't Starve server", category: 'games', longDescription: 'Survival game server with Together mode for multiplayer.' },
  { id: 'the-forest', name: 'The Forest', image: 'joker219/theforest:latest', defaultPort: 27015, description: 'The Forest game server', category: 'games', longDescription: 'Survival game server with build and survival mechanics.' },
  { id: 'conan-exiles', name: 'Conan Exiles', image: 'jamesits/conanexiles:latest', defaultPort: 27015, description: 'Conan Exiles server', category: 'games', longDescription: 'Open-world survival game server with building and PvP.' },
  { id: 'dayz', name: 'DayZ', image: 'jamesits/dayz:latest', defaultPort: 2302, description: 'DayZ game server', category: 'games', longDescription: 'Post-apocalyptic survival game server with persistence.' },
  { id: 'squad-game', name: 'Squad', image: 'jamesits/squad:latest', defaultPort: 27165, description: 'Squad game server', category: 'games', longDescription: 'Tactical shooter game server supporting 50v50 battles.' },
  { id: 'arma3', name: 'Arma 3', image: 'kube涛/arma3server:latest', defaultPort: 2302, description: 'Arma 3 game server', category: 'games', longDescription: 'Military simulation server with extensive modding capabilities.' },
  { id: 'vintage-story', name: 'Vintage Story', image: 'vinerymc/vintage-story:latest', defaultPort: 42424, description: 'Vintage Story server', category: 'games', longDescription: 'Vintage sandbox game server with crafting and survival.' },
  { id: 'core-keeper', name: 'Core Keeper', image: 'danielvanhaven/core-keeper:latest', defaultPort: 27015, description: 'Core Keeper server', category: 'games', longDescription: 'Mining sandbox game server with multiplayer support.' },
  { id: 'ground', name: 'The Ground', image: 'theground/ground:latest', defaultPort: 27015, description: 'The Ground server', category: 'games', longDescription: 'Custom survival game server framework.' },

];

export function getPresetsByCategory(category: AppCategory): AppPreset[] {
  return APP_PRESETS.filter(p => p.category === category)
}

export function findPresetById(id: string): AppPreset | undefined {
  return APP_PRESETS.find(p => p.id === id)
}

export function searchPresets(query: string): AppPreset[] {
  const lower = query.toLowerCase()
  return APP_PRESETS.filter(p => 
    p.name.toLowerCase().includes(lower) || 
    p.description.toLowerCase().includes(lower)
  )
}
