const KNOWN_LOGOS: Record<string, string> = {
  'redis': 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/redis/redis-original.svg',
  'postgres': 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/postgresql/postgresql-original.svg',
  'mysql': 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/mysql/mysql-original.svg',
  'mongodb': 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/mongodb/mongodb-original.svg',
  'mariadb': 'https://mariadb.com/wp-content/uploads/2021/12/mariadb-logo-Mono-Green.png',
  'nginx': 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/nginx/nginx-original.svg',
  'traefik': 'https://doc.traefik.io/traefik/assets/img/traefik.logo.svg',
  'rabbitmq': 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/rabbitmq/rabbitmq-original.svg',
  'grafana': 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/grafana/grafana-original.svg',
  'prometheus': 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/prometheus/prometheus-original.svg',
  'portainer': 'https://www.portainer.io/hubfs/Brand%20Assets/Logos/Logo-Polygon.svg',
  'registry': 'https://www.docker.com/wp-content/uploads/2022/03/Moby-logo.png',
  'wordpress': 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/wordpress/wordpress-original.svg',
  'ghost': 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/ghost/ghost-original.svg',
  'nextcloud': 'https://nextcloud.com/wp-content/themes/nextcloud/img/logo-icon.svg',
  'plex': 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/72/Plex_logo.svg/512px-Plex_logo.svg.png',
  'jellyfin': 'https://jellyfin.org/images/logo-icon.svg',
  'homeassistant': 'https://www.home-assistant.io/images/logo.svg',
  'minio': 'https://min.io/resources/img/logo.svg',
  'adguard': 'https://adguard.com/images/logos/adguard-home.svg',
  'vaultwarden': 'https://raw.githubusercontent.com/dani-garcia/vaultwarden/main/resources/vaultwarden-icon.svg',
  'strapi': 'https://strapi.io/assets/strapi-logo-light.svg',
  'directus': 'https://directus.io/assets/img/directus-logo.png',
  'gitea': 'https://gitea.io/images/gitea.svg',
  'gitlab': 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/gitlab/gitlab-original.svg',
  'jenkins': 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/jenkins/jenkins-original.svg',
  'mattermost': 'https://mattermost.com/wp-content/uploads/2022/06/logotype.svg',
  'rocketchat': 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/rocketchat/rocketchat-original.svg',
  'sonarr': 'https://sonarr.tv/assets/img/sonarr-logo.svg',
  'radarr': 'https://radarr.video/images/logo.svg',
  'qbittorrent': 'https://www.qbittorrent.org/img/logo/qbittorrent-2022.svg',
  'transmission': 'https://transmissionbt.com/assets/images/logo.png',
  'deluge': 'https://dev.deluge-torrent.org/changes/attachment/41/logo.png',
  'syncthing': 'https://syncthing.net/img/logo-horizontal.svg',
  'vault': 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/vault/vault-original.svg',
  'consul': 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/consul/consul-original.svg',
  'nomad': 'https://www.nomadproject.io/assets/img/logo-hashicorp.svg',
  'terraform': 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/terraform/terraform-original.svg',
  'ansible': 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/ansible/ansible-original.svg',
  'docker': 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/docker/docker-original.svg',
  'kubernetes': 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/kubernetes/kubernetes-plain.svg',
  'node': 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/nodejs/nodejs-original.svg',
  'nodejs': 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/nodejs/nodejs-original.svg',
  'python': 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/python/python-original.svg',
  'java': 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/java/java-original.svg',
  'rust': 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/rust/rust-original.svg',
  'go': 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/go/go-original.svg',
  'typescript': 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/typescript/typescript-original.svg',
  'react': 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/react/react-original.svg',
  'vue': 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/vuejs/vuejs-original.svg',
  'nextjs': 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/nextjs/nextjs-original.svg',
  'nuxt': 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/nuxtjs/nuxtjs-original.svg',
  'svelte': 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/svelte/svelte-original.svg',
  'vite': 'https://vitejs.dev/logo.svg',
  'tailwind': 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d5/Tailwind_CSS_Logo.svg/2048px-Tailwind_CSS_Logo.svg.png',
  'express': 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/express/express-original.svg',
  'fastapi': 'https://fastapi.tiangolo.com/img/icon-white.svg',
  'flask': 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/flask/flask-original.svg',
  'django': 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/django/django-original.svg',
  'laravel': 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/laravel/laravel-plain.svg',
  'spring': 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/spring/spring-original.svg',
  'maven': 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/maven/maven-original.svg',
  'gradle': 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/gradle/gradle-original.svg',
  'npm': 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/npm/npm-original-wordmark.svg',
  'yarn': 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/yarn/yarn-original.svg',
  'webpack': 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/webpack/webpack-original.svg',
  'babel': 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/babel/babel-original.svg',
  'jest': 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/jest/jest-plain.svg',
  'mocha': 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/mocha/mocha-plain.svg',
  'cypress': 'https://www.cypress.io/images/branding/cypress-logo-dark-text.svg',
  'selenium': 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/selenium/selenium-original.svg',
  'git': 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/git/git-original.svg',
  'github': 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/github/github-original.svg',
  'bitbucket': 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/bitbucket/bitbucket-original.svg',
  'jira': 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/jira/jira-original.svg',
  'confluence': 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/confluence/confluence-original.svg',
  'slack': 'https://a.slack-edge.com/80588/marketing/img/icons/icon_slack_hash_colored.png',
  'discord': 'https://assets-global.website-files.com/6257adef93867e50d84d30e2/636e0a6a49cf127bf92de1e2_icon_clyde_blurple_RGB.png',
  'kafka': 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/apachekafka/apachekafka-original.svg',
  'elasticsearch': 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/elasticsearch/elasticsearch-original.svg',
  'logstash': 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/logstash/logstash-original.svg',
  'kibana': 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/kibana/kibana-original.svg',
  'minecraft': 'https://www.minecraft.net/content/dam/minecraft/Minecraft_Logo.png',
  'steam': 'https://store.cloudflare.steamstatic.com/public/images/v8/logo_steam.svg',
  'unreal': 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/unrealengine/unrealengine-original.svg',
  'unity': 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/unity/unity-original.svg',
  'c++': 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/cplusplus/cplusplus-original.svg',
  'c': 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/c/c-original.svg',
  'csharp': 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/csharp/csharp-original.svg',
  'php': 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/php/php-original.svg',
  'ruby': 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/ruby/ruby-original.svg',
  'swift': 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/swift/swift-original.svg',
  'kotlin': 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/kotlin/kotlin-original.svg',
  'scala': 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/scala/scala-original.svg',
  'perl': 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/perl/perl-original.svg',
  'r': 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/r/r-original.svg',
  'matlab': 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/matlab/matlab-original.svg',
  'julia': 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/julia/julia-original.svg',
  'lua': 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/lua/lua-original.svg',
  'dart': 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/dart/dart-original.svg',
  'elixir': 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/elixir/elixir-original.svg',
  'haskell': 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/haskell/haskell-original.svg',
  'clojure': 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/clojure/clojure-original.svg',
  'erlang': 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/erlang/erlang-original.svg',
  'phoenix': 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/phoenixframework/phoenix-original.svg',
  'slim': 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/slim/slim-original.svg',
  'pylons': 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/pylons/pylons-original.svg',
  'pyramid': 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/pyramid/pyramid-original.svg',
  'falcon': 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/falcon/falcon-original.svg',
  'bottle': 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/bottle/bottle-original.svg',
  'cherrypy': 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/cherrypy/cherrypy-original.svg',
  'tornado': 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/tornado/tornado-original.svg',
  'aiohttp': 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/aiohttp/aiohttp-original.svg',
  'sanic': 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/sanic/sanic-original.svg',
  'starlette': 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/starlette/starlette-original.svg',
  'nestjs': 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/nestjs/nestjs-original.svg',
  'sails': 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/sails/sails-original.svg',
  'feathers': 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/feathers/feathers-original.svg',
  'totaljs': 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/totaljs/totaljs-original.svg',
  'loopback': 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/loopback/loopback-original.svg',
  'adonisjs': 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/adonisjs/adonisjs-original.svg',
  'keystone': 'https://keystonejs.com/keystone-logo.svg',
  'prisma': 'https://www.prisma.io/images/apple-touch-icon.png',
  'typeorm': 'https://typeorm.io/img/logo/logo-only.svg',
  'mongoose': 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/mongodb/mongodb-original.svg',
  'sequelize': 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/sequelize/sequelize-original.svg',
  'knex': 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/knex/knex-original.svg',
  'memcached': 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/memcached/memcached-original.svg',
  'cassandra': 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/cassandra/cassandra-original.svg',
  'couchbase': 'https://www.couchbase.com/assets/images/brand-resources/couchbase-lockup.svg',
  'dynamodb': 'https://a0.awsstatic.com/libra-css/images/logos/aws_logo_smile_1200x1200.png',
  'firebase': 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/firebase/firebase-plain.svg',
  'supabase': 'https://supabase.com/brand-assets/supabase-logo-wordmark--dark.svg',
  'appwrite': 'https://appwrite.io/images/logomark/logo-pink-gradient.svg',
  'phpmyadmin': 'https://www.phpmyadmin.net/static/images/logo.png',
  'adminer': 'https://www.adminer.org/static/logo.png',
  'dbeaver': 'https://dbeaver.io/wp-content/uploads/2015/09/beaver-head.png',
  'redisinsight': 'https://redis.com/wp-content/themes/wpx/assets/images/ri-icon.svg',
  'mongoclient': 'https://raw.githubusercontent.com/mongoclient/mongoclient/master/client/icons/icon_512x512.png',
  'rethinkdb': 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/rethinkdb/rethinkdb-original.svg',
  'arangodb': 'https://www.arangodb.com/wp-content/uploads/2021/02/ArangoDB_logo_2021_dark_blue.svg',
  'neo4j': 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/neo4j/neo4j-original.svg',
  'influxdb': 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/influxdb/influxdb-original.svg',
  'timescaledb': 'https://www.timescale.com/images/logo_timescale_database.svg',
  'cockroachdb': 'https://www.cockroachlabs.com/images/crdb-logo.svg',
  'yugabyte': 'https://www.yugabyte.com/images/yugabyte-db-logo.svg',
  'planetscale': 'https://planetscale.com/favicon.svg',
  'neon': 'https://neon.tech/favicon.svg',
  'upstash': 'https://upstash.com/static/favicon.ico',
  'railway': 'https://railway.app/brand/logo-light.png',
  'render': 'https://render.com/images/new-logo-dark.svg',
  'fly': 'https://fly.io/ui/images/brand/logo.svg',
  'vercel': 'https://assets.vercel.com/image/upload/v1588805858/repositories/vercel/logo.png',
  'netlify': 'https://www.netlify.com/v3/img/components/logomark.svg',
  'heroku': 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/heroku/heroku-original.svg',
  'digitalocean': 'https://www.digitalocean.com/assets/fonts/branding-footer/svg/DO_Logo_horizontal_blue.svg',
  'aws': 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/amazonwebservices/amazonwebservices-original.svg',
  'azure': 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/azure/azure-original.svg',
  'gcp': 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/googlecloud/googlecloud-original.svg',
  'oracle': 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/oracle/oracle-original.svg',
  'ibm': 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/ibm/ibm-original.svg',
  'alibaba': 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/alibabacloud/alibabacloud-original-wordmark.svg',
  'tencent': 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/tencentcloud/tencentcloud-original.svg',
  'huawei': 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/huaweicloud/huaweicloud-original.svg',

  // App presets – databases & admin
  'orientdb': 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/orientdb/orientdb-original.svg',
  'sqlite3': 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/sqlite/sqlite-original.svg',
  'pgadmin4': 'https://www.pgadmin.org/static/img/logo.ico',
  'cloudbeaver': 'https://dbeaver.io/wp-content/uploads/2015/09/beaver-head.png',

  // Monitoring & proxy
  'uptimekuma': 'https://github.com/louislam/uptime-kuma/raw/master/public/icon.svg',
  'glances': 'https://nicolargo.github.io/glances/logo.png',
  'netdata': 'https://raw.githubusercontent.com/netdata/netdata/master/web/gui/v2/src/assets/netdata-logomark.svg',
  'loki': 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/grafana/grafana-original.svg',
  'alertmanager': 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/prometheus/prometheus-original.svg',
  'thanos': 'https://thanos.io/img/thanos-logo.svg',
  'cadvisor': 'https://www.kubernetes.io/images/favicon.png',
  'unificontroller': 'https://ui.com/favicon.ico',
  'speedtest': 'https://www.speedtest.net/favicon.ico',
  'watchtower': 'https://containrrr.dev/watchtower/img/watchtower.svg',
  'ws': 'https://cockpit-project.org/images/cockpit-icon.svg',
  'webmin': 'https://www.webmin.com/images/webmin.png',
  'httpd': 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/apache/apache-original.svg',
  'caddy': 'https://caddyserver.com/resources/images/favicon.png',
  'haproxy': 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/haproxy/haproxy-original.svg',
  'varnish': 'https://varnish-cache.org/images/varnish-cache.png',
  'squid': 'https://www.squid-cache.org/favicon.ico',
  'envoy': 'https://www.envoyproxy.io/img/envoy-logo.svg',
  'nginxproxymanager': 'https://nginxproxymanager.com/favicon.ico',

  // Storage & backup
  'filebrowser': 'https://filebrowser.org/images/icon.svg',
  'seafilemc': 'https://www.seafile.com/favicon.ico',
  'pydiocore': 'https://pydio.com/favicon.ico',
  'duplicati': 'https://www.duplicati.com/favicon.ico',
  'restserver': 'https://restic.net/img/restic-logo.svg',
  'borgmatic': 'https://torsion.org/borgmatic/images/borgmatic-logo.svg',
  'veejay': 'https://veejayhq.org/veejay.png',

  // Media
  'pmsdocker': 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/72/Plex_logo.svg/512px-Plex_logo.svg.png',
  'embyserver': 'https://emby.media/favicon.ico',
  'tautulli': 'https://tautulli.com/images/tautulli-logo.svg',
  'jackett': 'https://github.com/Jackett/Jackett/raw/master/Logo.png',
  'bazarr': 'https://www.bazarr.media/images/logo.png',
  'overseerr': 'https://overseerr.dev/logo.svg',
  'metube': 'https://github.com/axcore/metube/raw/master/metube.png',
  'sabnzbd': 'https://sabnzbd.org/images/logo.png',
  'nzbget': 'https://nzbget.net/images/logo.png',
  'ombi': 'https://ombi.io/img/logo.svg',
  'photoprism': 'https://www.photoprism.app/favicon.ico',
  'immichserver': 'https://immich.app/img/immich-logo.svg',
  'librephotos': 'https://github.com/LibrePhotos/librephotos/raw/develop/frontend/public/logo.svg',
  'piwigo': 'https://piwigo.org/themes/default/images/logo.png',
  'snapdrop': 'https://github.com/RobinLinus/snapdrop/raw/master/client/public/android-chrome-192x192.png',

  // Home automation
  'iobroker': 'https://www.iobroker.net/favicon.ico',
  'openhab': 'https://www.openhab.org/favicon.ico',
  'nodered': 'https://nodered.org/about/resources/media/node-red-icon.svg',
  'mosquitto': 'https://mosquitto.org/images/mosquitto-logo.svg',
  'zigbee2mqtt': 'https://www.zigbee2mqtt.io/images/logo.svg',
  'frigate': 'https://frigate.video/img/logo.svg',
  'scrypted': 'https://github.com/koush/scrypted/raw/main/apps/desktop/icon.png',
  'homebridge': 'https://homebridge.io/favicon.ico',
  'amd64homeassistant': 'https://www.home-assistant.io/images/logo.svg',
  'adguardhome': 'https://adguard.com/images/logos/adguard-home.svg',

  // Security
  'authelia': 'https://www.authelia.com/images/authelia-logo.svg',
  'traefikforwardauth': 'https://doc.traefik.io/traefik/assets/img/traefik.logo.svg',
  'openvpnas': 'https://openvpn.net/favicon.ico',
  'crowdsec': 'https://crowdsec.net/images/logo_crowdsec.svg',
  'fail2ban': 'https://www.fail2ban.org/favicon.ico',
  'clamav': 'https://www.clamav.net/favicon.ico',
  'oauth2proxy': 'https://oauth2-proxy.github.io/oauth2-proxy/img/logos/OAuth2-Proxy-logo.svg',
  'iologtosdklocal': 'https://logto.io/favicon.ico',

  // CMS & wikis
  'grav': 'https://getgrav.org/images/logo.svg',
  'hub': 'https://prismic.io/favicon.ico',
  'sanity': 'https://www.sanity.io/static/images/favicons/favicon-32x32.png',
  'squidex': 'https://squidex.io/favicon.ico',
  'apostrophe': 'https://apostrophecms.com/favicon.ico',
  'payload': 'https://payloadcms.com/favicon.ico',
  'wiki': 'https://js.wiki/favicon.ico',
  'bookstack': 'https://www.bookstackapp.com/favicon.ico',
  'xwiki': 'https://www.xwiki.org/xwiki/bin/download/Main/WebHome/xwiki.png',
  'dokuwiki': 'https://www.dokuwiki.org/lib/images/dokuwiki-128.png',
  'mediawiki': 'https://www.mediawiki.org/static/images/favicon/favicon.ico',

  // DevOps
  'gitlabce': 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/gitlab/gitlab-original.svg',
  'woodpeckerserver': 'https://woodpecker-ci.org/img/logo.svg',
  'argocd': 'https://argo-cd.readthedocs.io/en/stable/assets/logo.png',
  'gitlabrunner': 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/gitlab/gitlab-original.svg',
  'harborcore': 'https://goharbor.io/img/logos/harbor-icon-color.svg',
  'nexus3': 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/sonatype/sonatype-original.svg',
  'dashboard': 'https://tekton.dev/img/tekton-logo.svg',
  'bitwardenrs': 'https://raw.githubusercontent.com/dani-garcia/vaultwarden/main/resources/vaultwarden-icon.svg',
  'waypoint': 'https://www.waypointproject.io/img/waypoint-logo.svg',
  'boundary': 'https://boundaryproject.io/img/logo.svg',
  'gocdserver': 'https://www.gocd.org/assets/images/go_logo-5f653b28.svg',
  'dagger': 'https://dagger.io/img/dagger-logo.svg',

  // Communication
  'mattermostteamdition': 'https://mattermost.com/wp-content/uploads/2022/06/logotype.svg',
  'elementweb': 'https://element.io/favicon.ico',
  'bbbweb': 'https://bigbluebutton.org/wp-content/themes/bigbluebutton/images/logo.png',
  'signalserver': 'https://signal.org/favicon.ico',
  'conduit': 'https://conduit.rs/logo.svg',
  'hydrogenweb': 'https://element.io/favicon.ico',
  'nhekoreborn': 'https://nheko.re/nheko.svg',
  'weechat': 'https://weechat.org/images/weechat.png',
  'znc': 'https://znc.in/favicon.ico',
  'inspircd': 'https://www.inspircd.org/favicon.ico',
  'unrealircd': 'https://www.unrealircd.org/images/unrealircd.svg',
  'prosody': 'https://prosody.im/images/prosody-logo.svg',
  'ecs': 'https://www.ejabberd.im/favicon.ico',
  'matterbridge': 'https://github.com/42wim/matterbridge/raw/master/docs/logo.png',

  // Other – productivity & analytics
  'gotify': 'https://gotify.net/img/gotify-logo.svg',
  'ntfy': 'https://ntfy.sh/img/ntfy.png',
  'calcom': 'https://cal.com/favicon.ico',
  'linkding': 'https://github.com/sissbruecker/linkding/raw/master/static/logo.svg',
  'shlink': 'https://shlink.io/favicon.ico',
  'wallabag': 'https://www.wallabag.it/favicon.ico',
  'freshrss': 'https://freshrss.org/favicon.ico',
  'vikunja': 'https://vikunja.io/images/vikunja-icon.svg',
  'wekan': 'https://wekan.github.io/favicon.ico',
  'app': 'https://plane.so/favicon.ico',
  'kanboard': 'https://kanboard.org/favicon.ico',
  'trilium': 'https://github.com/zadam/trilium/raw/master/src/public/images/trilium.svg',
  'budibase': 'https://budibase.com/favicon.ico',
  'tooljet': 'https://www.tooljet.com/favicon.ico',
  'appsmithce': 'https://www.appsmith.com/favicon.ico',
  'analytics': 'https://plausible.io/img/favicon.ico',
  'matomo': 'https://matomo.org/img/favicon.ico',
  'countlyserver': 'https://countly.com/favicon.ico',
  'posthog': 'https://posthog.com/favicon.ico',
  'ackee': 'https://ackee.electerious.com/favicon.ico',
  'fathom': 'https://usefathom.com/favicon.ico',
  'metabase': 'https://www.metabase.com/favicon.ico',
  'superset': 'https://superset.apache.org/img/superset-logo-horiz.svg',
  'redash': 'https://redash.io/favicon.ico',
  'basenotebook': 'https://jupyter.org/favicon.ico',
  'rstudio': 'https://posit.co/wp-content/themes/posit/assets/images/site-logo.svg',
  'codeserver': 'https://code-server.dev/favicon.ico',
  'streamlit': 'https://streamlit.io/favicon.ico',
  'mlflow': 'https://mlflow.org/docs/latest/_static/MLflow-logo-final-black.svg',
  'cpkafka': 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/apachekafka/apachekafka-original.svg',
  'vernemq': 'https://vernemq.com/images/logo.png',
  'airflow': 'https://airflow.apache.org/images/airflow-logo.png',
  'prefect': 'https://www.prefect.io/favicon.ico',
  'dagster': 'https://dagster.io/favicon.ico',
  'temporal': 'https://temporal.io/favicon.ico',
  'pipedream': 'https://pipedream.com/favicon.ico',
  'activepieces': 'https://www.activepieces.com/favicon.ico',
  'webinyserverlesscms': 'https://www.webiny.com/favicon.ico',
  'verdaccio': 'https://verdaccio.org/img/verdaccio-tiny.svg',
  'artifactoryoss': 'https://jfrog.com/favicon.ico',
  'ghorg': 'https://github.com/gabrie30/ghorg/raw/master/logo.png',

  // Game servers (preset images resolve to these repo names)
  'minecraftserver': 'https://www.minecraft.net/content/dam/minecraft/Minecraft_Logo.png',
  'minecraftbedrockserver': 'https://www.minecraft.net/content/dam/minecraft/Minecraft_Logo.png',
  'steamcmd': 'https://store.cloudflare.steamstatic.com/public/images/v8/logo_steam.svg',
  'trino': 'https://trinodb.io/img/trino.svg',
  'panel': 'https://pterodactyl.io/img/logo.svg',
}

const cachedLogos: Record<string, string> = {}

/** Preset id → logo URL for presets whose image name is ambiguous (e.g. server, hub, app) */
const PRESET_LOGO_OVERRIDES: Record<string, string> = {
  'owncloud': 'https://owncloud.com/wp-content/themes/owncloud/assets/img/favicon.ico',
  'authentik': 'https://goauthentik.io/img/icon.png',
  'prismic': 'https://prismic.io/favicon.ico',
  'plane': 'https://plane.so/favicon.ico',
  'tekton': 'https://tekton.dev/img/tekton-logo.svg',
}

function getImageName(image: string): string {
  const name = image.split(':')[0].split('/').pop()?.toLowerCase() || ''
  return name.replace(/-/g, '').replace(/_/g, '')
}

export async function fetchDockerHubLogo(image: string, presetId?: string): Promise<string | null> {
  if (presetId && PRESET_LOGO_OVERRIDES[presetId]) {
    return PRESET_LOGO_OVERRIDES[presetId]
  }

  const imageName = getImageName(image)
  
  if (cachedLogos[imageName]) return cachedLogos[imageName]
  
  if (KNOWN_LOGOS[imageName]) {
    cachedLogos[imageName] = KNOWN_LOGOS[imageName]
    return KNOWN_LOGOS[imageName]
  }
  
  for (const [key, logo] of Object.entries(KNOWN_LOGOS)) {
    if (imageName.includes(key) || key.includes(imageName)) {
      cachedLogos[imageName] = logo
      return logo
    }
  }
  
  return null
}
